#!/command/with-contenv sh
exec 2>&1
export HOME=/home/user
export SWARMFLEET_TOOLS_ROOT="${SWARMFLEET_TOOLS_ROOT:-/home/user/.swarmfleet/tools}"
export PATH="/command:/usr/local/sbin:/usr/local/bin:$SWARMFLEET_TOOLS_ROOT/bin:$SWARMFLEET_TOOLS_ROOT/npm/bin:$SWARMFLEET_TOOLS_ROOT/python/bin:/usr/sbin:/usr/bin:/sbin:/bin"
exec /usr/local/bin/swarmfleet-tool-manager
