#!/usr/bin/env node

/**
 * Version generation script
 */

import { readFileSync, writeFileSync } from "node:fs";
import process from "node:process";

try {
  const packageJson = JSON.parse(readFileSync("package.json", "utf-8"));
  const version = packageJson.version;

  const versionFileContent = `// Auto-generated file - do not edit manually
// This file is generated by scripts/generate-version.js
export const VERSION = "${version}";
`;

  writeFileSync("cli/version.ts", versionFileContent);

  console.log(`Generated cli/version.ts with version: ${version}`);
} catch (error) {
  console.error("Failed to generate version.ts:", error.message);
  process.exit(1);
}
